### ISSUE TITLE
module import vs direct import enforcement for tests

### ISSUE THREAD

**Issue by Zarkopafilis** [bitaesthetics/algotrading-api#1]
As per [this question](https://stackoverflow.com/questions/57957456/flask-request-mocker-patch-object-does-not-take-effect/58028871#58028871) and the first unit test being added at [this commit](https://github.com/bitaesthetics/algotrading-api/commit/94123c333c1d3306f7dc0b1fbf00e0943f741c02), it would be good if we did not enforce module imports at both the test and the endpoint level, for flask objects that get captured by a proxy, thus requiring context.

**Comment by Zarkopafilis** [comment]
@deepettas any update on this?

**Comment by deepettas** [comment]
Not from my side

**Comment by Zarkopafilis** [comment]
Direct import for up to 3 components. Module import for more. Can we settle on this for start?

**Comment by deepettas** [comment]
Sounds like a plan.
